export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const POST_MESSAGES_REQUEST = "POST_MESSAGES_REQUEST";
export const POST_MESSAGES_SUCCESS = "POST_MESSAGES_SUCCESS";
export const POST_MESSAGES_FAIL = "POST_MESSAGES_FAIL";
